language: erlang

sudo: required

before_install:
  - git clone https://github.com/erlang/rebar3.git
  - pushd .
  - cd rebar3
  - ./bootstrap
  - sudo mv rebar3 /usr/local/bin/
  - popd

notifications:
  email: false

otp_release:
  - 18.2.1
  - 17.5

script:
  - make vsn-check
  - make
  - make xref
  - make edoc
  - make distclean
  - rebar get-deps
  - rebar compile
  - make distclean
  - rebar3 compile
# test with snappy disabled
  - make distclean
  - export KAFKA_PROTOCOL_NO_SNAPPY=1
  - make vsn-check
  - make xref
  - make distclean
  - rebar get-deps
  - rebar compile
  - make distclean
  - rebar3 compile

