language: erlang

sudo: required

before_install:
  - |
    git clone https://github.com/erlang/rebar3.git
    pushd .
    cd rebar3
    ./bootstrap
    sudo mv rebar3 /usr/local/bin/
    popd
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-precise main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - sudo docker info

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - make
  - make xref
  - make edoc
  - make dialyze
  - export KAFKA_VERSION=1.1  && make testbed && make eunit
  - export KAFKA_VERSION=1.0  && make testbed && make eunit
  - export KAFKA_VERSION=0.11 && make testbed && make eunit
  - export KAFKA_VERSION=0.10 && make testbed && make eunit
  - export KAFKA_VERSION=0.9  && make testbed && export KPRO_TEST_KAFKA_09=1 && make eunit
  - make cover

